config/routes.rb
Rails.application.routes.draw do
  resources :dailycashes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dailycash.rb
class Dailycash < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dailycashes_controller.rb
class DailycashesController < ApplicationController
  before_action :set_dailycash, only: [:show, :edit, :update, :destroy]

  # GET /dailycashes
  # GET /dailycashes.json
  def index
    @dailycashes = Dailycash.all
  end

  # GET /dailycashes/1
  # GET /dailycashes/1.json
  def show
  end

  # GET /dailycashes/new
  def new
    @dailycash = Dailycash.new
  end

  # GET /dailycashes/1/edit
  def edit
  end

  # POST /dailycashes
  # POST /dailycashes.json
  def create
    @dailycash = Dailycash.new(dailycash_params)

    respond_to do |format|
      if @dailycash.save
        format.html { redirect_to @dailycash, notice: 'Dailycash was successfully created.' }
        format.json { render :show, status: :created, location: @dailycash }
      else
        format.html { render :new }
        format.json { render json: @dailycash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dailycashes/1
  # PATCH/PUT /dailycashes/1.json
  def update
    respond_to do |format|
      if @dailycash.update(dailycash_params)
        format.html { redirect_to @dailycash, notice: 'Dailycash was successfully updated.' }
        format.json { render :show, status: :ok, location: @dailycash }
      else
        format.html { render :edit }
        format.json { render json: @dailycash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dailycashes/1
  # DELETE /dailycashes/1.json
  def destroy
    @dailycash.destroy
    respond_to do |format|
      format.html { redirect_to dailycashes_url, notice: 'Dailycash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dailycash
      @dailycash = Dailycash.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dailycash_params
      params.require(:dailycash).permit(:date, :sale, :visa, :discount, :cashpurchase, :onlinepaidorder, :totaldriverpayout, :banklodgment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dailycashes_helper.rb
module DailycashesHelper
end

app/views/dailycashes/_form.html.erb
<%= form_for(dailycash) do |f| %>
  <% if dailycash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dailycash.errors.count, "error") %> prohibited this dailycash from being saved:</h2>

      <ul>
      <% dailycash.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :sale %>
    <%= f.number_field :sale %>
  </div>

  <div class="field">
    <%= f.label :visa %>
    <%= f.number_field :visa %>
  </div>

  <div class="field">
    <%= f.label :discount %>
    <%= f.number_field :discount %>
  </div>

  <div class="field">
    <%= f.label :cashpurchase %>
    <%= f.number_field :cashpurchase %>
  </div>

  <div class="field">
    <%= f.label :onlinepaidorder %>
    <%= f.number_field :onlinepaidorder %>
  </div>

  <div class="field">
    <%= f.label :totaldriverpayout %>
    <%= f.number_field :totaldriverpayout %>
  </div>

  <div class="field">
    <%= f.label :banklodgment %>
    <%= f.number_field :banklodgment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dailycashes/edit.html.erb
<h1>Editing Dailycash</h1>

<%= render 'form', dailycash: @dailycash %>

<%= link_to 'Show', @dailycash %> |
<%= link_to 'Back', dailycashes_path %>

app/views/dailycashes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dailycashes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Sale</th>
      <th>Visa</th>
      <th>Discount</th>
      <th>Cashpurchase</th>
      <th>Onlinepaidorder</th>
      <th>Totaldriverpayout</th>
      <th>Banklodgment</th>
      <th>Overunder</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% running_total = 0 %>
    <% @dailycashes.each do |dailycash| %>
      <tr>
        <td><%= dailycash.date %></td>
        <td><%= dailycash.sale %></td>
        <td><%= dailycash.visa %></td>
        <td><%= dailycash.discount %></td>
        <td><%= dailycash.cashpurchase %></td>
        <td><%= dailycash.onlinepaidorder %></td>
        <td><%= dailycash.totaldriverpayout %></td>
        <td><%= dailycash.banklodgment %></td>
        <td><%= dailycash.sale - (dailycash.visa + dailycash.discount + dailycash.cashpurchase + dailycash.onlinepaidorder + dailycash.totaldriverpayout + dailycash.banklodgment )%></td>
        <td><%= link_to 'Show', dailycash %></td>
        <td><%= link_to 'Edit', edit_dailycash_path(dailycash) %></td>
        <td><%= link_to 'Destroy', dailycash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dailycash', new_dailycash_path %>

app/views/dailycashes/new.html.erb
<h1>New Dailycash</h1>

<%= render 'form', dailycash: @dailycash %>

<%= link_to 'Back', dailycashes_path %>

app/views/dailycashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @dailycash.date %>
</p>

<p>
  <strong>Sale:</strong>
  <%= @dailycash.sale %>
</p>

<p>
  <strong>Visa:</strong>
  <%= @dailycash.visa %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @dailycash.discount %>
</p>

<p>
  <strong>Cashpurchase:</strong>
  <%= @dailycash.cashpurchase %>
</p>

<p>
  <strong>Onlinepaidorder:</strong>
  <%= @dailycash.onlinepaidorder %>
</p>

<p>
  <strong>Totaldriverpayout:</strong>
  <%= @dailycash.totaldriverpayout %>
</p>

<p>
  <strong>Banklodgment:</strong>
  <%= @dailycash.banklodgment %>
</p>

<%= link_to 'Edit', edit_dailycash_path(@dailycash) %> |
<%= link_to 'Back', dailycashes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>